export {
    CustomIcon,
    HomeIcon,
    UserIcon,
    GuarantorIcon,
    LoanIcon,
    DecisionIcon,
    SavingsIcon,
    LoanRequestIcon,
    WhiteListIcon,
    KarmaIcon,
    BriefCaseIcon,
    SavingsProductIcon,
    FeesChargesIcon,
    TransactionIcon,
    ServicesIcon,
    ServiceAccountIcon,
    SettlementIcon,
    ReportIcon,
    PreferenceIcon,
    FeesPricingIcon,
    AuditIcon,
    Pablo2,
    MessagingIcon,
    LogoutIcon
  } from './svg';
  